export const ROUTE_PATH = {
  performance: '/performance',
  performanceOverview: '/performance/overview',
  overview: '/',
  home: '/',
  login: '/login',
  userStatic: '/user-static',
  performanceDetail: '/performance/detail',
  performanceList: '/performance/list',
  requestException: '/exception/request',
  resourceException: '/exception/resource',
  requestExceptionList: '/exception/request/list',
  exception: '/exception',
  exceptionList: '/exception/list',
  jsExceptionList: '/exception/js/list',
  jsException: '/exception/js',
  resourceExceptionList: '/exception/resource/list',
};
